// Definitions.h

#ifndef START_APP_NAMESPACE_DEFINITIONS_H
#define START_APP_NAMESPACE_DEFINITIONS_H

namespace START_APP_NAMESPACE
{
    constexpr auto LOG_DIR = "./Log/";
}

#endif //START_APP_NAMESPACE_DEFINITIONS_H
